/* ============================================================
   PORTAL ZAG — Casos ZIG (Blog de Fracasos)
   Datos reales de campañas que hicieron zig y los textos de la
   interfaz. Todo el texto se inserta con textContent (nada de
   innerHTML con datos).
   ============================================================ */

window.ZAG_CASOS = (function () {
  'use strict';

  var categorias = [
    'Producto', 'Branding', 'Packaging', 'Identidad visual',
    'UX/UI', 'Producto digital', 'Spot publicitario',
    'Influencer marketing', 'Campaña navideña', 'Redes sociales',
    'Pauta digital', 'Copywriting', 'Promoción', 'Retail',
    'Activación', 'Rebranding',
  ];

  var ui = {
    kicker: 'BLOG DE FRACASOS · CASOS REALES',
    title: ['MARCAS REALES.', 'ZIGS REALES.'],
    titleAccent: 'ZIG',
    sub: 'Campañas de marcas enormes que hicieron zig cuando debían hacer zag. Aquí no se esconden: se estudian.',
    scroll: 'Baja y mira quién hizo zig ↓',

    accesoKicker: 'SOLO PARA LA TRIBU',
    accesoTitulo: 'Los Casos ZIG son solo para la tribu.',
    accesoCopy: 'Activa tu perfil ZAG para estudiar cada fracaso y su lección.',
    accesoCta1: 'Activar mi perfil',
    accesoCta2: 'Entrar en modo demo',
    accesoLabel: 'Elige tu nivel de la demo',
    accesoHint: 'Solo para la demo: el nivel no cambia tu perfil real.',
    accesoLevelAria: 'Nivel de la demo',

    sessionAria: 'Sesión en modo demo',
    sessionExit: 'Salir de la demo',

    marcaMeta: 'Campaña · ',   /* "New Coke · 1985" */
    verCaso: 'Ver el caso real ↗',
    sourceLabel: 'Fuente: ',
    debatePill: 'En debate',
    debateNote: 'Las conclusiones sobre este caso siguen discutiéndose.',

    bloques: {
      quePaso: 'Qué pasó',
      resultado: 'El resultado',
      zag: 'El ZAG que faltó',
    },

    ctaKicker: '30 AÑOS ROMPIENDO LO OBVIO',
    ctaTitle: '¿CONOCES OTRO ZIG?',
    ctaSub: 'Manda el caso que conozcas',
    ctaBtn: 'Manda el caso que conozcas',
    ctaClose: 'Cerrar',
    form: {
      marca: 'Marca',
      marcaPh: '¿Qué marca hizo zig?',
      campana: 'Campaña y año',
      campanaPh: 'Ej.: "Rediseño de logo" · 2010',
      categoria: 'Categoría',
      categoriaOpt: 'Elige una categoría',
      quePaso: '¿Qué pasó?',
      quePasoPh: 'Contanos brevemente qué hizo y qué resultado tuvo.',
      link: 'Link de la fuente',
      linkPh: 'https://…',
      send: 'Enviar caso',
      ok: 'Recibido. El equipo ZAG lo revisa y, si es un zig de verdad, lo publicamos.',
      errMarca: 'Falta el nombre de la marca.',
      errQuePaso: 'Contanos qué pasó (máximo 400 caracteres).',
      errLink: 'El link de la fuente no parece ser una URL válida.',
      maxQuePaso: 400,
    },

    starza: '✦',
    vinylText: '¿SOLO PORQUE ZIG…?',

    /* Índices de los temas por tarjeta: la tarjeta N usa el tema N % 5 */
    temas: ['t1', 't2', 't3', 't4', 't5'],
  };

  var casos = [
    {
      id: 'new-coke',
      marca: 'Coca-Cola',
      campana: 'New Coke',
      anio: 1985,
      categorias: ['Producto', 'Branding'],
      hook: 'Cambiaron una fórmula de 99 años y el país entero la pidió de vuelta.',
      quePaso: 'Para frenar a Pepsi en las pruebas de sabor, Coca-Cola reemplazó su fórmula original por una más dulce. En pruebas a ciegas ganaba; en la calle, la gente sintió que le estaban quitando algo suyo: miles de llamadas y cartas de protesta, y compras de pánico de la Coca-Cola de siempre.',
      resultado: 'La fórmula original volvió como \u201cCoca-Cola Classic\u201d.',
      datoDuro: '79 días',
      leccion: 'Una marca no es solo un producto: es memoria. Las pruebas a ciegas miden el sabor, no el apego.',
      fuente: { medio: 'The Coca-Cola Company', url: 'https://www.coca-colacompany.com/about-us/history/new-coke-the-most-memorable-marketing-blunder-ever' },
    },
    {
      id: 'tropicana',
      marca: 'Tropicana',
      campana: 'Rediseño de empaque',
      anio: 2009,
      categorias: ['Packaging', 'Branding'],
      hook: 'Un empaque tan \u201climpio\u201d que la gente ya no encontraba su jugo.',
      quePaso: 'Tropicana cambió su empaque icónico, la naranja con el pitillo, por un diseño minimalista con un vaso de jugo. En la góndola se confundía con marcas genéricas y los clientes se quejaron de que no lo reconocían.',
      resultado: 'Las ventas cayeron y la marca regresó al empaque anterior en cuestión de semanas.',
      datoDuro: '≈ −20 % en ventas',
      leccion: 'El empaque es la cara con la que te reconocen en tres segundos. Minimalismo sin reconocimiento es invisibilidad.',
      fuente: { medio: 'Packaging Digest', url: 'https://www.packagingdigest.com/beverage-packaging/tropicana-redesign-failure-take-two' },
    },
    {
      id: 'gap-logo',
      marca: 'Gap',
      campana: 'Nuevo logo',
      anio: 2010,
      categorias: ['Branding', 'Identidad visual'],
      hook: 'Un logo que duró una semana.',
      quePaso: 'Gap cambió de un día para otro su clásico cuadro azul por un logo en Helvetica con un pequeño degradado. Internet lo destrozó, aparecieron cuentas parodia y la marca intentó salvarlo pidiéndole a la gente que propusiera diseños, lo que empeoró las críticas.',
      resultado: 'Gap volvió a su logo original.',
      datoDuro: '≈ 1 semana',
      leccion: 'Si cambias tu identidad sin contar el porqué, otros van a contar la historia por ti.',
      fuente: { medio: 'NBC News', url: 'https://www.nbcnews.com/id/wbna39622202' },
    },
    {
      id: 'pepsi-live-for-now',
      marca: 'Pepsi',
      campana: 'Live for Now con Kendall Jenner',
      anio: 2017,
      categorias: ['Spot publicitario', 'Influencer marketing'],
      hook: 'Una lata de Pepsi para \u201cresolver\u201d una protesta social.',
      quePaso: 'El comercial mostraba a Kendall Jenner dejando una sesión de fotos para unirse a una marcha y ofrecerle una Pepsi a un policía para bajar la tensión. Fue criticado por trivializar movimientos de protesta reales como Black Lives Matter.',
      resultado: 'Pepsi retiró el comercial y pidió disculpas públicamente.',
      datoDuro: 'Retirado al día siguiente',
      leccion: 'Usar una causa social como decorado se lee como oportunismo. Si no es tu causa, no es tu escenario.',
      fuente: { medio: 'CNBC', url: 'https://www.cnbc.com/2017/04/05/kendall-jenners-pepsi-ad-causes-twitter-storm-labeled-disrespectful.html' },
    },
    {
      id: 'peloton',
      marca: 'Peloton',
      campana: 'The Gift That Gives Back',
      anio: 2019,
      categorias: ['Spot publicitario', 'Campaña navideña'],
      hook: 'Un regalo de Navidad que internet leyó como una indirecta.',
      quePaso: 'El comercial mostraba a una mujer grabando en video su año usando la bicicleta que le regaló su esposo. Muchos lo leyeron como sexista y como presión sobre el cuerpo; se volvió meme en cuestión de horas.',
      resultado: 'La acción de Peloton cayó al día siguiente, aunque después se debatió si el comercial realmente afectó las ventas.',
      datoDuro: '≈ −9 % en bolsa en un día',
      leccion: 'El tono lo decide quien lo ve, no quien lo hace. Prueba tu idea con gente que no está en tu reunión.',
      fuente: { medio: 'Fortune', url: 'https://fortune.com/2019/12/04/peloton-stock-falls-after-backlash-gift-that-gives-ad' },
    },
    {
      id: 'snapchat-redesign',
      marca: 'Snapchat',
      campana: 'Rediseño de la app',
      anio: 2018,
      categorias: ['UX/UI', 'Producto digital'],
      hook: 'Un rediseño que nadie pidió y un tuit de 1.300 millones de dólares.',
      quePaso: 'Snapchat reorganizó la app mezclando las historias de amigos con el contenido de medios. Más de un millón de usuarios firmaron una petición para revertirlo, y Kylie Jenner tuiteó que ya casi no lo abría.',
      resultado: 'Snap perdió valor en bolsa el mismo día del tuit y siguió recibiendo críticas por meses.',
      datoDuro: '≈ US$1.300 M en un día',
      leccion: 'En UX, cambiar los hábitos de la gente sin escucharla es como cambiarle los muebles de la casa mientras duerme.',
      fuente: { medio: 'CNN Business', url: 'https://www.cnn.com/videos/cnnmoney/2018/02/24/kylie-jenner-tweet-snapchat-stock-orig.cnn' },
    },
    {
      id: 'mcdstories',
      marca: 'McDonald\u2019s',
      campana: '#McDStories',
      anio: 2012,
      categorias: ['Redes sociales', 'Pauta digital'],
      hook: 'Pagaron un hashtag para que la gente contara sus peores historias.',
      quePaso: 'McDonald\u2019s promocionó en Twitter el hashtag #McDStories esperando historias bonitas sobre sus proveedores y clientes. Los usuarios lo llenaron de anécdotas negativas y quejas.',
      resultado: 'La marca retiró la promoción muy rápido, pero el hashtag siguió vivo durante días.',
      datoDuro: 'Promoción retirada en ≈ 2 horas',
      leccion: 'Una conversación abierta no se controla. Si pagas pauta para una pregunta abierta, prepárate para cualquier respuesta.',
      fuente: { medio: 'Forbes', url: 'https://www.forbes.com/sites/kashmirhill/2012/01/24/mcdstories-when-a-hashtag-becomes-a-bashtag/' },
    },
    {
      id: 'burger-king-iwd',
      marca: 'Burger King UK',
      campana: 'Tuit del Día de la Mujer',
      anio: 2021,
      categorias: ['Redes sociales', 'Copywriting'],
      hook: 'El titular decía \u201cLas mujeres pertenecen a la cocina\u201d. La explicación nadie la leyó.',
      quePaso: 'Burger King UK usó esa frase para anunciar un programa de becas para mujeres chefs, pero la explicación estaba en el siguiente tuit del hilo. En redes, la primera línea circuló sola.',
      resultado: 'La marca borró el tuit y pidió disculpas.',
      datoDuro: 'Tuit eliminado + disculpa pública',
      leccion: 'En redes, cada frase se lee sola. Provocar con un tema sensible sin contexto es regalar el titular.',
      fuente: { medio: 'Adweek', url: 'https://www.adweek.com/brand-marketing/burger-king-apologizes-and-deletes-tweet-that-said-women-belong-in-the-kitchen/' },
    },
    {
      id: 'hoover-vuelos',
      marca: 'Hoover',
      campana: 'Vuelos gratis',
      anio: 1992,
      categorias: ['Promoción', 'Retail'],
      hook: 'Compra una aspiradora y vuela gratis a Estados Unidos. ¿Qué podía salir mal?',
      quePaso: 'Hoover, en Reino Unido, ofreció dos tiquetes de avión por comprar productos desde £100. La gente compró aspiradoras solo por los vuelos y la empresa no tuvo cómo cumplir con tanta demanda.',
      resultado: 'Pérdidas millonarias, directivos despedidos y años de reclamos de clientes.',
      datoDuro: '≈ £48 M de costo',
      leccion: 'Una promoción se diseña con los números del peor escenario, no con los del mejor.',
      fuente: { medio: 'Campaign', url: 'https://www.campaignlive.co.uk/article/history-advertising-no-141-hoovers-free-flights-voucher/1356868' },
    },
    {
      id: 'pepsi-number-fever',
      marca: 'Pepsi Filipinas',
      campana: 'Number Fever',
      anio: 1992,
      categorias: ['Promoción', 'Activación'],
      hook: 'Un número premiado que, por error, estaba impreso en cientos de miles de tapas.',
      quePaso: 'El concurso prometía hasta un millón de pesos filipinos al número ganador. Salió el 349, pero por un error de sistema ese número estaba impreso en cientos de miles de tapas. Pepsi no pagó el premio completo a todos y ofreció una compensación menor.',
      resultado: 'Protestas masivas, ataques contra camiones y plantas, miles de demandas, y personas que perdieron la vida en los disturbios.',
      datoDuro: 'Miles de demandas',
      leccion: 'En una activación masiva, el control de calidad también es parte de la campaña. Un error operativo se vuelve crisis de marca.',
      fuente: { medio: 'CBC Radio', url: 'https://www.cbc.ca/radio/undertheinfluence/the-bottle-cap-snafu-that-nearly-cost-pepsi-32-billion-1.6305749' },
    },
    {
      id: 'jaguar-copy-nothing',
      marca: 'Jaguar',
      campana: 'Copy Nothing',
      anio: 2024,
      categorias: ['Branding', 'Rebranding'],
      debate: true,
      hook: 'Un rebranding que decía \u201cno copies nada\u201d… y nadie entendió qué vendía.',
      quePaso: 'Para su etapa eléctrica, Jaguar lanzó un logo nuevo y un video con modelos en ropa de colores sin mostrar un solo carro, bajo el lema \u201cCopy Nothing\u201d. Llovieron críticas en redes, entre ellas la de Elon Musk.',
      resultado: 'La marca defendió que buscaba atención y la consiguió, pero perdió conexión con muchos de sus clientes.',
      datoDuro: 'Caso en debate',
      leccion: 'Hacer ZAG no es borrar todo lo que eras. La diferencia tiene que conectar con algo que la gente ya valora.',
      fuente: { medio: 'Fortune', url: 'https://fortune.com/2024/11/20/jaguar-brand-campaign-evs-elon-musk' },
    },
  ];

  return { ui: ui, casos: casos, categorias: categorias };
})();