/* ============================================================
   PORTAL ZAG — Proyectos fuera del ZIG
   Datos demo + textos de interfaz. Se expone en
   window.ZAG_PROYECTOS. Los links de ejemplo son de relleno:
   cuando lleguen los proyectos reales, se reemplazan acá.
   ============================================================ */

window.ZAG_PROYECTOS = (function () {
  'use strict';

  var CATEGORIAS = [
    'Branding',
    'Campaña 360',
    'Pauta digital',
    'Social media',
    'UX/UI',
    'Audiovisual',
    'Packaging',
    'Activación',
    'Fotografía',
  ];

  var PROYECTOS = [
    {
      id: 'tostadora-quindio',
      titulo: 'Tostadora Caturra: del alegro al ácido',
      extracto: 'Rebranding de una tostadora de café del Quindío. Le sacamos lo premium de laboratorio y le dejamos el territorio. El empaque nuevo se volvió el regalo de fin de año de media región.',
      categorias: ['Branding', 'Packaging'],
      autor: { nombre: 'Mariana Ocampo', iniciales: 'MO', nivel: 'master' },
      equipo: ['Julián Vélez', 'Sara Montoya'],
      fecha: '2026-03-12',
      semestre: '7° sem',
      periodo: '2026-1',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://www.behance.net/',
      destino: 'behance',
      cover: null,
      pinned: true,
    },
    {
      id: 'fogata-360',
      titulo: 'Fogata Zaggista, la que no se apaga',
      extracto: 'Campaña 360 de la Fogata Zaggista: preventa, contenido en vivo y una instalación de tres metros en el campus. Se anotaron 900 personas en tres semanas sin un peso en publicidad.',
      categorias: ['Campaña 360', 'Activación'],
      autor: { nombre: 'Daniel Ospina', iniciales: 'DO', nivel: 'creator' },
      equipo: ['Equipo Fogata'],
      fecha: '2026-02-28',
      semestre: '8° sem',
      periodo: '2026-1',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://drive.google.com/',
      destino: 'drive',
      cover: null,
      pinned: true,
    },
    {
      id: 'pauta-meta-moda',
      titulo: 'Cuatro euros, mil resultados',
      extracto: 'Pauta en Meta Ads para un emprendimiento de moda local. Con cuatro euros diarios llegamos a 12.000 personas y duplicamos las ventas en el segundo mes, sin subir el presupuesto.',
      categorias: ['Pauta digital'],
      autor: { nombre: 'Valentina Ríos', iniciales: 'VR', nivel: 'strategist' },
      equipo: [],
      fecha: '2025-11-14',
      semestre: '6° sem',
      periodo: '2025-2',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://www.behance.net/',
      destino: 'behance',
      cover: null,
    },
    {
      id: 'parqueaderos-app',
      titulo: 'Parquea fácil: UX de una app en Armenia',
      extracto: 'Rediseño de UX de una app de parqueaderos. Sacamos tres pasos del registro, mostramos el precio antes de iniciar y el tiempo de sesión bajó a menos de 40 segundos.',
      categorias: ['UX/UI'],
      autor: { nombre: 'Carlos Eduardo Gómez', iniciales: 'CG', nivel: 'rookie' },
      equipo: ['Ana Sofía'],
      fecha: '2025-10-02',
      semestre: '4° sem',
      periodo: '2025-2',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://www.behance.net/',
      destino: 'behance',
      cover: null,
    },
    {
      id: 'dulces-tipicos',
      titulo: 'Dulces del Valle, la vitrina de la abuela',
      extracto: 'Packaging de dulces típicos quindianos. Cada bolsa cuenta una receta de familia. Hecho a mano igual que antes, pero ahora se entiende que eso vale oro.',
      categorias: ['Packaging'],
      autor: { nombre: 'Lucía Restrepo', iniciales: 'LR', nivel: 'senior' },
      equipo: ['Daniel Botero', 'Manuela C.'],
      fecha: '2026-01-22',
      semestre: '9° sem',
      periodo: '2026-1',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://drive.google.com/',
      destino: 'drive',
      cover: null,
    },
    {
      id: 'documental-30-anos',
      titulo: 'Treinta años rompiendo lo obvio',
      extracto: 'Documental corto sobre los 30 años del programa. Once egresados cuentan el momento exacto en que el sistema los cambió. Una hora y media que se ven como ocho minutos.',
      categorias: ['Audiovisual'],
      autor: { nombre: 'Tomás Agudelo', iniciales: 'TA', nivel: 'master' },
      equipo: ['Estudiantes de documental'],
      fecha: '2025-12-05',
      semestre: '7° sem',
      periodo: '2025-2',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://drive.google.com/',
      destino: 'drive',
      cover: null,
    },
    {
      id: 'museo-del-zig',
      titulo: 'Museo del Zig, la segunda vida de un afiche',
      extracto: 'Activación donde combinamos un afiche de publicidad genérica de los 90 con vitrina, luz y audio. Lo que no tenía nada que decir quedó expuesto.',
      categorias: ['Activación', 'Audiovisual'],
      autor: { nombre: 'Isabella Parra', iniciales: 'IP', nivel: 'creator' },
      equipo: ['Caro Bullet', 'Nicolás'],
      fecha: '2026-01-30',
      semestre: '8° sem',
      periodo: '2026-1',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://www.behance.net/',
      destino: 'behance',
      cover: null,
    },
    {
      id: 'foto-producto',
      titulo: 'La foto que sí compró',
      extracto: 'Fotografía de producto para una marca local de skincare. Cambiamos el fondo blanco por una mesa real con sombra dura, y la conversión se triplicó.',
      categorias: ['Fotografía'],
      autor: { nombre: 'Juan Sebastián López', iniciales: 'JL', nivel: 'rookie' },
      equipo: [],
      fecha: '2025-09-18',
      semestre: '4° sem',
      periodo: '2025-2',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://www.behance.net/',
      destino: 'behance',
      cover: null,
    },
    {
      id: 'tiktok-hostal',
      titulo: 'Hostal Bonita Suerte en TikTok',
      extracto: 'Contenido de TikTok para un hostal en el Quindío. Series cortas, no anuncios. Pasamos de 200 a 6.000 seguidores en un mes y la ocupación se volvió constante.',
      categorias: ['Social media'],
      autor: { nombre: 'Mariana Ocampo', iniciales: 'MO', nivel: 'strategist' },
      equipo: ['Salomé B.'],
      fecha: '2026-02-10',
      semestre: '7° sem',
      periodo: '2026-1',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://www.behance.net/',
      destino: 'behance',
      cover: null,
    },
    {
      id: 'ropa-upcycled',
      titulo: 'Rehilacha, ropa que ya se había gastado',
      extracto: 'Branding de una marca de ropa upcycled. La historia de no tirar, contada sin culpa y con el precio a la vista. Tres tallas menos en bodega y cero desperdicio.',
      categorias: ['Branding', 'Social media'],
      autor: { nombre: 'Lucía Restrepo', iniciales: 'LR', nivel: 'senior' },
      equipo: ['Taller Rehilacha'],
      fecha: '2025-10-24',
      semestre: '6° sem',
      periodo: '2025-2',
      // TODO: reemplazar por el link real del proyecto
      link: 'https://drive.google.com/',
      destino: 'drive',
      cover: null,
    },
  ];

  var UI = {
    heroKicker: 'Proyectos Zaggistas',
    heroTitle: 'FUERA DEL',
    heroTitleAccent: 'ZIG',
    heroFraseAntes: 'Lo que hacen los zaggistas cuando viven',
    heroFraseAccent: 'la filosofía del ZAG',
    heroFraseDespues: '.',
    heroHintDesktop: 'Mueve el cursor',
    heroHintMobile: 'Desliza el dedo',
    filtrosKicker: 'PROYECTOS FUERA DEL ZIG',
    filtrosTitle: 'Lo mejor de la tribu',
    contadorUno: 'proyecto',
    contadorVarios: 'proyectos',
    searchPh: 'Busca por proyecto, autor o categoría…',
    searchAria: 'Buscar proyectos',
    cats: ['Todos'].concat(CATEGORIAS),
    nivelAria: 'Filtrar por nivel del autor',
    niveles: ['Todos', 'Rookie', 'Strategist', 'Creator', 'Master', 'Senior'],
    ordenAria: 'Ordenar proyectos',
    ordenRecientes: 'Más recientes',
    ordenAntiguos: 'Más antiguos',
    limpiar: 'Limpiar filtros',
    vacioTitulo: 'Nada por aquí todavía',
    vacioCopy: '¿Y si el primero en hacer zag eres tú?',
    vacioCta: 'Subir mi proyecto',
    verProyecto: 'Ver proyecto',
    badgeDestacado: '📌 Destacado por el equipo ZAG',
    badgeRevision: '⏳ En revisión',
    bellLabel: 'Notificaciones',
    bellTitulo: 'Tus envíos',
    bellVacio: 'Todavía no enviaste ningún proyecto.',
    bellPendientes: 'En revisión',
    simularAprobacion: '(demo) simular aprobación',
    destinoBehance: 'Behance',
    destinoDrive: 'Google Drive',
    formKicker: '¿HICISTE ZAG?',
    formTitle: 'Sube tu proyecto',
    formSub: 'Si rompiste lo obvio, la tribu tiene que verlo.',
    formSinSesion: 'Activa tu perfil ZAG para subir proyectos',
    formActivar: 'Activar mi perfil',
    formDemo: 'Entrar en modo demo',
    formDemoHint: 'Elige tu nivel para activar el perfil demo.',
    fTitulo: 'Título del proyecto',
    fTituloPh: 'Ej.: Rebranding de una tostadora del Quindío',
    fDesc: 'Descripción',
    fDescPh: 'Cuéntanos brevemente qué hiciste y qué pasó.',
    fCat: 'Categoría',
    fCatPh: 'Elige hasta 3',
    fLink: 'Link del proyecto',
    fLinkPh: 'https://…',
    fLinkHint: 'Puedes enviar el link del proyecto en Drive, Behance, web, etc.',
    fPortada: 'Imagen de portada (opcional)',
    fEquipo: 'Equipo / coautores (opcional)',
    fEquipoPh: 'Escribe un nombre y presiona Enter',
    avisoLegal:
      'Entiendo que mi proyecto quedará público en el Portal ZAG, visible para cualquier persona. Los derechos de autor siguen siendo de sus creadores: el Portal ZAG solo lo muestra con crédito y con enlace a su fuente original. Confirmo que tengo permiso de mis coautores (y del cliente, si aplica) para compartirlo.',
    enviar: 'Enviar propuesta',
    enviando: 'Enviando…',
    resetDemo: 'Reiniciar demo',
    modTitulo: '¡Recibido!',
    modCopy: 'Tu proyecto entra en revisión. El equipo ZAG lo aprueba en máx. 48 horas.',
    modCta: 'Entendido',
    errTitulo: 'Ponle un título (máximo 80 caracteres).',
    errDesc: 'Cuéntanos un poquito más (máximo 280 caracteres).',
    errCat: 'Elige al menos una categoría.',
    errLink: 'Ponle un link válido, empezando por https://',
    errLinkDrive: "Asegúrate de que el archivo esté compartido como 'Cualquier persona con el enlace'.",
    errLegal: 'Tienes que aceptar el aviso para publicar.',
    errPortadaPeso: 'Esa imagen pesa más de 2 MB.',
    warnPortadaRatio: 'No es 16:9. La recortamos al centro, pero se ve mejor si lo es.',
    errEquipo: 'Máximo 6 coautores.',
    specsTitulo: 'Especificaciones de la portada',
    specs: [
      'Formato horizontal 16:9, mínimo 1600 × 900 px.',
      'JPG, PNG o WebP, máximo 2 MB.',
      'Debe mostrar la pieza principal del proyecto (mockup, key visual o frame clave).',
      'Sin textos pequeños, marcos, bordes ni marcas de agua: la etiqueta y el título ya los pone el portal.',
      'Nada de collages recargados: una imagen, una idea.',
    ],
    specsFooter: 'Si no subes portada, usamos una portada ZAG automática.',
  };

  return {
    categorias: CATEGORIAS,
    proyectos: PROYECTOS,
    ui: UI,
  };
})();
